services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    platform: linux/amd64
    image: adminer
    restart: always
    ports:
      - 8080:8080
